namespace GES.Source.Mvvm.Converters
{
    using GES.Content;
    using System;
    using System.Globalization;
    using System.Windows.Data;

    public class ItemToNameConverter : IValueConverter
    {
        public Object Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
        {
            if (parameter != null)
            {
                value = parameter;
            }

            if (value is UInt16)
            {
                UInt16 itemId  = (UInt16) value;

                switch(itemId)
                {
                    case 0x0000: return "<None>";
                    case 0x0001: return "Copper Sword";
                    case 0x0002: return "Iron Sword";
                    case 0x0003: return "Steel Blade";
                    case 0x0004: return "Feather Saber";
                    case 0x0005: return "Bastard Sword";
                    case 0x0006: return "Defender";
                    case 0x0007: return "Rune Blade";
                    case 0x0008: return "Excalibur";
                    case 0x0009: return "Ragnarok";
                    case 0x000A: return "Treasured Sword";
                    case 0x000B: return "Father's Sword";
                    case 0x000C: return "Marr Sword";
                    case 0x000D: return "Test 1 (Unused)"; // Test me
                    case 0x000E: return "Test 2 (Unused)"; // Test me
                    case 0x000F: return "Ultima Sword";
                    case 0x0010: return "Equipment 116 (Name?)"; // Test me
                    case 0x0011: return "Equipment 117 (Name?)"; // Test me
                    case 0x0012: return "Iron Lance";
                    case 0x0013: return "Partisan";
                    case 0x0014: return "Sonic Lance";
                    case 0x0015: return "Titan Lance";
                    case 0x0016: return "Halberd";
                    case 0x0017: return "Highwind";
                    case 0x0018: return "Dragon Lance";
                    case 0x0019: return "Dragoon Spear";
                    case 0x001A: return "Gungnir";
                    case 0x001B: return "Longinus";
                    case 0x001C: return "Treasured Spear";
                    case 0x001D: return "Father's Spear";
                    case 0x001E: return "Marr Spear";
                    case 0x001F: return "Ultima Lance";
                    case 0x0020: return "Equipment 119 (Unused)";
                    case 0x0021: return "Equipment 120 (Unused)";
                    case 0x0022: return "Equipment 121 (Unused)";
                    case 0x0023: return "Equipment 122 (Unused)";
                    case 0x0024: return "Orc Hammer";
                    case 0x0025: return "Wave Hammer";
                    case 0x0026: return "Rune Hammer";
                    case 0x0027: return "Goblin Hammer";
                    case 0x0028: return "Sonic Hammer";
                    case 0x0029: return "Prism Hammer";
                    case 0x002A: return "Mythril Hammer";
                    case 0x002B: return "Mystic Hammer";
                    case 0x002C: return "Treasured Hammer";
                    case 0x002D: return "Father's Hammer";
                    case 0x002E: return "Marr Hammer";
                    case 0x002F: return "Ultima Hammer";
                    case 0x0030: return "Equipment 124 (Unused)";
                    case 0x0031: return "Equipment 125 (Unused)";
                    case 0x0032: return "Equipment 126 (Unused)";
                    case 0x0033: return "Equipment 127 (Unused)";
                    case 0x0034: return "Aura Racket";
                    case 0x0035: return "Solid Racket";
                    case 0x0036: return "Dual Shooter";
                    case 0x0037: return "Elemental Cudgel";
                    case 0x0038: return "Steel Cudgel";
                    case 0x0039: return "Prism Bludgeon";
                    case 0x003A: return "Butterfly Head";
                    case 0x003B: return "Queen's Heel";
                    case 0x003C: return "Dreamcatcher";
                    case 0x003D: return "Treasured Maul";
                    case 0x003E: return "Father's Maul";
                    case 0x003F: return "Marr Maul";
                    case 0x0040: return "Ultima Maul";
                    case 0x0041: return "Equipment 129 (Unused)";
                    case 0x0042: return "Equipment 130 (Unused)";
                    case 0x0043: return "Equipment 131 (Unused)";
                    case 0x0044: return "Equipment 132 (Unused)";
                    case 0x0045: return "Travel Clothes";
                    case 0x0046: return "Bronze Plate";
                    case 0x0047: return "Iron Plate";
                    case 0x0048: return "Mythril Hauberk";
                    case 0x0049: return "Flame Mail";
                    case 0x004A: return "Frost Mail";
                    case 0x004B: return "Storm Mail";
                    case 0x004C: return "Time Mail";
                    case 0x004D: return "Eternal Mail";
                    case 0x004E: return "Blessed Mail";
                    case 0x004F: return "Saintly Mail";
                    case 0x0050: return "Gold Mail";
                    case 0x0051: return "Crystal Mail";
                    case 0x0052: return "Diamond Plate";
                    case 0x0053: return "Gaia Plate (Clavat)";
                    case 0x0054: return "Mystic Armor (Unused)";
                    case 0x0055: return "Taterskin Coat (Unused)";
                    case 0x0056: return "Coat (Unused)";
                    case 0x0057: return "Oversized Coat (Unused)";
                    case 0x0058: return "Makeshift Shield";
                    case 0x0059: return "Iron Shield";
                    case 0x005A: return "Mythril Shield";
                    case 0x005B: return "Flame Shield";
                    case 0x005C: return "Frost Shield";
                    case 0x005D: return "Storm Shield";
                    case 0x005E: return "Saintly Shield";
                    case 0x005F: return "Diamond Shield";
                    case 0x0060: return "Rune Shield";
                    case 0x0061: return "Chocobo Shield";
                    case 0x0062: return "Gauntlets";
                    case 0x0063: return "Bronze Gauntlets";
                    case 0x0064: return "Iron Gauntlets";
                    case 0x0065: return "Mythril Gauntlets";
                    case 0x0066: return "Flame Armlets";
                    case 0x0067: return "Frost Armlets";
                    case 0x0068: return "Storm Armlets";
                    case 0x0069: return "Gold Armlets";
                    case 0x006A: return "Diamond Armlets";
                    case 0x006B: return "Helm";
                    case 0x006C: return "Bronze Helm";
                    case 0x006D: return "Iron Helm";
                    case 0x006E: return "Mythril Helm";
                    case 0x006F: return "Flame Helm";
                    case 0x70: return "Frost Helm";
                    case 0x71: return "Storm Helm";
                    case 0x72: return "Time Helm";
                    case 0x73: return "Eternal Helm";
                    case 0x74: return "Diamond Helm";
                    case 0x75: return "Old Belt";
                    case 0x76: return "Bronze Belt";
                    case 0x77: return "Iron Belt";
                    case 0x78: return "Mythril Belt";
                    case 0x79: return "Flame Sash";
                    case 0x7A: return "Frost Sash";
                    case 0x7B: return "Storm Sash";
                    case 0x7C: return "Blessed Sash";
                    case 0x7D: return "Winged Belt";
                    case 0x7E: return "Diamond Belt";
                    case 0x7F: return "Badge of the Flame";
                    case 0x80: return "Badge of the Frost";
                    case 0x81: return "Badge of the Thunderbolt";
                    case 0x82: return "Accurate Watch";
                    case 0x83: return "Unfaltering Watch";
                    case 0x84: return "Blue Misanga";
                    case 0x85: return "White Misanga";
                    case 0x86: return "Gold Necklace";
                    case 0x87: return "Charm of Wisdom (Yuke)";
                    case 0x88: return "Talisman of Wisdom (Clavat)";
                    case 0x89: return "Flower Bracer (Female)";
                    case 0x8A: return "Charm of Speed (Selkie)";
                    case 0x8B: return "Talisman of Speed (Selkie)";
                    case 0x8C: return "Thief's Emblem (Selkie)";
                    case 0x8D: return "Headband of Zeal (Male)";
                    case 0x8E: return "Daemon's Earring (Yuke)";
                    case 0x8F: return "Devil's Earring (Clavat)";
                    case 0x90: return "Pixie's Earring (Lilty)";
                    case 0x91: return "Angel's Earring (Selkie)";
                    case 0x92: return "Crystal Ring";
                    case 0x93: return "Twisted Spectacles (Yuke)";
                    case 0x94: return "Twisted Scope (Clavat)";
                    case 0x95: return "Headband of Healing (Male)";
                    case 0x96: return "Jade Bracer (Female)";
                    case 0x97: return "Power Goggles (Lilty)";
                    case 0x98: return "Eagle Goggles (Selkie)";
                    case 0x99: return "Lion's Heart (Lilty)";
                    case 0x9A: return "Dragon's Heart (Lilty)";
                    case 0x9B: return "Wizard's Soul (Yuke)";
                    case 0x9C: return "Bishop's Soul (Yuke)";
                    case 0x9D: return "Elemental's Soul (Yuke)";
                    case 0x9E: return "Force Ring";
                    case 0x9F: return "Shuriken";
                    case 0xA0: return "Maneater";
                    case 0xA1: return "Double Axe";
                    case 0xA2: return "Ashura";
                    case 0xA3: return "Kaiser Knuckles";
                    case 0xA4: return "Flametongue";
                    case 0xA5: return "Ice Brand";
                    case 0xA6: return "Loaded Dice";
                    case 0xA7: return "Ogrekiller";
                    case 0xA8: return "Engetsurin";
                    case 0xA9: return "Sasuke's Blade";
                    case 0xAA: return "Mjollnir";
                    case 0xAB: return "Masquerade";
                    case 0xAC: return "Murasame";
                    case 0xAD: return "Masamune";
                    case 0xAE: return "Gekkabijin";
                    case 0xAF: return "Onion Sword";
                    case 0xB0: return "Power Wristband";
                    case 0xB1: return "Green Beret";
                    case 0xB2: return "Fang Charm";
                    case 0xB3: return "Twisted Headband";
                    case 0xB4: return "Heavy Armband";
                    case 0xB5: return "Giant's Glove";
                    case 0xB6: return "Dragon's Whisker";
                    case 0xB7: return "Mage Masher";
                    case 0xB8: return "Rune Staff";
                    case 0xB9: return "Book of Light";
                    case 0xBA: return "Sage's Staff";
                    case 0xBB: return "Wonder Wand";
                    case 0xBC: return "Rune Bell";
                    case 0xBD: return "Mage's Staff";
                    case 0xBE: return "Noah's Lute";
                    case 0xBF: return "Galatyn";
                    case 0xC0: return "Tome of Ultima";
                    case 0xC1: return "Silver Bracer";
                    case 0xC2: return "Cat's Bell";
                    case 0xC3: return "Faerie Ring";
                    case 0xC4: return "Winged Cap";
                    case 0xC5: return "Candy Ring";
                    case 0xC6: return "Kris";
                    case 0xC7: return "Red Slippers";
                    case 0xC8: return "Dark Matter";
                    case 0xC9: return "Gold Hairpin";
                    case 0xCA: return "Taotie Motif";
                    case 0xCB: return "Ribbon";
                    case 0xCC: return "Main Gauche";
                    case 0xCD: return "Chicken Knife";
                    case 0xCE: return "Save the Queen";
                    case 0xCF: return "Drill";
                    case 0xD0: return "Buckler";
                    case 0xD1: return "Silver Spectacles";
                    case 0xD2: return "Sparkling Bracer";
                    case 0xD3: return "Black Hood";
                    case 0xD4: return "Helm of Arai";
                    case 0xD5: return "Elven Mantle";
                    case 0xD6: return "Wonder Bangle";
                    case 0xD7: return "Ring of Protection";
                    case 0xD8: return "Aegis";
                    case 0xD9: return "Rat's Tail";
                    case 0xDA: return "Teddy Bear";
                    case 0xDB: return "Moogle Pocket";
                    case 0xDC: return "Chocobo Pocket";
                    case 0xDD: return "Gobbie Pocket";
                    case 0xDE: return "Ultimate Pocket";
                    case 0xDF: return "Ring of Fire";
                    case 0xE0: return "Ring of Blizzard";
                    case 0xE1: return "Ring of Thunder";
                    case 0xE2: return "Ring of Cure";
                    case 0xE3: return "Ring of Life";
                    case 0xE4: return "Earth Pendant";
                    case 0xE5: return "Moon Pendant";
                    case 0xE6: return "Star Pendant";
                    case 0xE7: return "Sun Pendant";
                    case 0xE8: return "Equipment 187 (Unused)";
                    case 0xE9: return "Equipment 188 (Unused)";
                    case 0xEA: return "Equipment 189 (Unused)";
                    case 0xEB: return "Equipment 190 (Unused)";
                    case 0xEC: return "Equipment 191 (Unused)";
                    case 0xED: return "Equipment 192 (Unused)";
                    case 0xEE: return "Equipment 193 (Unused)";
                    case 0xEF: return "Equipment 194 (Unused)";
                    case 0xF0: return "Equipment 195 (Unused)";
                    case 0xF1: return "Equipment 196 (Unused)";
                    case 0xF2: return "Equipment 197 (Unused)";
                    case 0xF3: return "Equipment 198 (Unused)";
                    case 0xF4: return "Equipment 199 (Unused)";
                    case 0xF5: return "Equipment 200 (Unused)";
                    case 0xF6: return "Equipment 201 (Unused)";
                    case 0xF7: return "Equipment 202 (Unused)";
                    case 0xF8: return "Equipment 203 (Unused)";
                    case 0xF9: return "Equipment 204 (Unused)";
                    case 0xFA: return "Equipment 205 (Unused)";
                    case 0xFB: return "Equipment 206 (Unused)";
                    case 0xFC: return "Equipment 207 (Unused)";
                    case 0xFD: return "Equipment 208 (Unused)";
                    case 0xFE: return "Equipment 209 (Unused)";
                    case 0xFF: return "Equipment 210 (Unused)";
                    case 0x100: return "Stone of Fire";
                    case 0x101: return "Stone of Blizzard";
                    case 0x102: return "Stone of Thunder";
                    case 0x103: return "Stone of ??? (Ulticite)";
                    case 0x104: return "Stone of Slow (Unused)";
                    case 0x105: return "Stone of Cure";
                    case 0x106: return "Stone of Clear";
                    case 0x107: return "Stone of Life";
                    case 0x108: return "Stone of Holy (Unused)";
                    case 0x109: return "Stone of Stop (Unused)";
                    case 0x10A: return "Stone of Gravity (Unused)";
                    case 0x10B: return "Curse (Unused)";
                    case 0x10C: return "Illness (Unused)";
                    case 0x10D: return "Magic Circle (Unused)";
                    case 0x10E: return "Ultima (Unused)";
                    case 0x10F: return "Flare (Unused)";
                    case 0x110: return "Meteor (Unused)";
                    case 0x111: return "Darkness (Unused)";
                    case 0x112: return "Zeal (Unused)";
                    case 0x113: return "Seize (Unused)";
                    case 0x114: return "Confuse (Unused)";
                    case 0x115: return "Whirlwind (Unused)";
                    case 0x116: return "Examine (Unused)";
                    case 0x117: return "Threaten (Unused)";
                    case 0x118: return "Favorites (Unused)";
                    case 0x119: return "Dice (Unused)";
                    case 0x11A: return "Blame (Unused)";
                    case 0x11B: return "Rule (Unused)";
                    case 0x11C: return "All (Unused)";
                    case 0x11D: return "Fan (Unused)";
                    case 0x11E: return "Circle (Unused)";
                    case 0x11F: return "Trail (Unused)";
                    case 0x120: return "Enhance (Unused)";
                    case 0x121: return "Double (Unused)";
                    case 0x122: return "Add (Unused)";
                    case 0x123: return "Reflect (Unused)";
                    case 0x124: return "Barrier (Unused)";
                    case 0x125: return "Phoenix Down";
                    case 0x126: return "Bronze";
                    case 0x127: return "Iron";
                    case 0x128: return "Mythril";
                    case 0x129: return "Orichalcum";
                    case 0x12A: return "Diamond Ore";
                    case 0x12B: return "Gold";
                    case 0x12C: return "Silver";
                    case 0x12D: return "Bronze Shard";
                    case 0x12E: return "Iron Shard";
                    case 0x12F: return "Tiny Crystal";
                    case 0x130: return "Crystal Ball";
                    case 0x131: return "Ruby";
                    case 0x132: return "Jade";
                    case 0x133: return "Alloy";
                    case 0x134: return "Magma Rock";
                    case 0x135: return "Chilly Gel";
                    case 0x136: return "Thunderball";
                    case 0x137: return "Holy Water";
                    case 0x138: return "Heavenly Dust";
                    case 0x139: return "Yellow Feather";
                    case 0x13A: return "Blue Silk";
                    case 0x13B: return "White Silk";
                    case 0x13C: return "Fiend's Claw";
                    case 0x13D: return "Devil's Claw";
                    case 0x13E: return "Faerie's Tear";
                    case 0x13F: return "Angel's Tear";
                    case 0x140: return "Ancient Sword";
                    case 0x141: return "Cursed Crook";
                    case 0x142: return "Orc Belt";
                    case 0x143: return "King's Scale";
                    case 0x144: return "Green Sphere";
                    case 0x145: return "Dragon's Fang";
                    case 0x146: return "Malboro Seed";
                    case 0x147: return "Desert Fang";
                    case 0x148: return "Wind Crystal";
                    case 0x149: return "Ethereal Orb";
                    case 0x14A: return "Red Eye";
                    case 0x14B: return "Dweomer Spore";
                    case 0x14C: return "Lord's Robe";
                    case 0x14D: return "Griffin's Wing";
                    case 0x14E: return "Cerberus Fang";
                    case 0x14F: return "Needle";
                    case 0x150: return "Hard Shell";
                    case 0x151: return "Worm Antenna";
                    case 0x152: return "Toad Oil";
                    case 0x153: return "Jagged Scythe";
                    case 0x154: return "Ogre Fang";
                    case 0x155: return "Chimera's Horn";
                    case 0x156: return "Crop Seed (Unused)";
                    case 0x157: return "Coeurl Whisker";
                    case 0x158: return "Zu's Beak";
                    case 0x159: return "Cockatrice Scale";
                    case 0x15A: return "Ancient Potion";
                    case 0x15B: return "Shiny Shard";
                    case 0x15C: return "Gigas Claw";
                    case 0x15D: return "Gear";
                    case 0x15E: return "Pressed Flower";
                    case 0x15F: return "Remedy";
                    case 0x160: return "Goddess Statuette (Unused)";
                    case 0x161: return "Devil's Mask (Unused)";
                    case 0x162: return "Extra 22 (Unused)";
                    case 0x163: return "Flower Seed";
                    case 0x164: return "Strange Seed";
                    case 0x165: return "Fruit Seed (1)";
                    case 0x166: return "Fruit Seed (2)";
                    case 0x167: return "Fruit Seed (3)";
                    case 0x168: return "Vegetable Seed (1)";
                    case 0x169: return "Vegetable Seed (2)";
                    case 0x16A: return "Vegetable Seed (3)";
                    case 0x16B: return "Wheat Seed";
                    case 0x16C: return "Worn Bandanna";
                    case 0x16D: return "Shella Mark";
                    case 0x16E: return "Kilanda Sulfur";
                    case 0x16F: return "Cactus Flower";
                    case 0x170: return "Extra 23 (Unused)";
                    case 0x171: return "Ultimite";
                    case 0x172: return "Dark Sphere";
                    case 0x173: return "Extra 24 (Unused)";
                    case 0x174: return "Extra 25 (Unused)";
                    case 0x175: return "Extra 26 (Unused)";
                    case 0x176: return "Extra 27 (Unused)";
                    case 0x177: return "Extra 28 (Unused)";
                    case 0x178: return "Extra 29 (Unused)";
                    case 0x179: return "Extra 30 (Unused)";
                    case 0x17A: return "Extra 31 (Unused)";
                    case 0x17B: return "Extra 32 (Unused)";
                    case 0x17C: return "Extra 33 (Unused)";
                    case 0x17D: return "Striped Apple";
                    case 0x17E: return "Cherry Cluster";
                    case 0x17F: return "Rainbow Grapes";
                    case 0x180: return "Star Carrot";
                    case 0x181: return "Gourd Potato";
                    case 0x182: return "Round Corn";
                    case 0x183: return "Meat";
                    case 0x184: return "Fish";
                    case 0x185: return "Bannock";
                    case 0x186: return "Spring Water";
                    case 0x187: return "Milk";
                    case 0x188: return "Strange Liquid";
                    case 0x189: return "Flame Shard (Unused)";
                    case 0x18A: return "Water Shard (Unused)";
                    case 0x18B: return "Lightning Shard (Unused)";
                    case 0x18C: return "Darkness Shard (Unused)";
                    case 0x18D: return "Wheat";
                    case 0x18E: return "Flour";
                    case 0x18F: return "??? (Unused)";
                    case 0x190: return "Item Gil (Unused)";
                    case 0x191: return "Novice's Weapon";
                    case 0x192: return "Warrior's Weapon";
                    case 0x193: return "Valiant Weapon";
                    case 0x194: return "Mighty Weapon";
                    case 0x195: return "Victorious Weapon";
                    case 0x196: return "Master's Weapon";
                    case 0x197: return "Legendary Weapon";
                    case 0x198: return "Hero's Weapon";
                    case 0x199: return "Celestial Weapon";
                    case 0x19A: return "Dark Weapon";
                    case 0x19B: return "Lunar Weapon";
                    case 0x19C: return "Bronze Armor";
                    case 0x19D: return "Iron Armor";
                    case 0x19E: return "Mythril Armor";
                    case 0x19F: return "Flame Armor";
                    case 0x1A0: return "Frost Armor";
                    case 0x1A1: return "Lightning Armor";
                    case 0x1A2: return "Time Armor";
                    case 0x1A3: return "Eternal Armor";
                    case 0x1A4: return "Pure Armor";
                    case 0x1A5: return "Holy Armor";
                    case 0x1A6: return "Gold Armor";
                    case 0x1A7: return "Radiant Armor";
                    case 0x1A8: return "Diamond Armor";
                    case 0x1A9: return "Earth Armor";
                    case 0x1AA: return "Iron Shield";
                    case 0x1AB: return "Mythril Shield";
                    case 0x1AC: return "Flame Shield";
                    case 0x1AD: return "Frost Shield";
                    case 0x1AE: return "Lightning Shield";
                    case 0x1AF: return "Holy Shield";
                    case 0x1B0: return "Diamond Shield";
                    case 0x1B1: return "Magic Shield";
                    case 0x1B2: return "Legendary Shield";
                    case 0x1B3: return "Bronze Gloves";
                    case 0x1B4: return "Iron Gloves";
                    case 0x1B5: return "Mythril Gloves";
                    case 0x1B6: return "Flame Gloves";
                    case 0x1B7: return "Frost Gloves";
                    case 0x1B8: return "Lightning Gloves";
                    case 0x1B9: return "Gold Gloves";
                    case 0x1BA: return "Diamond Gloves";
                    case 0x1BB: return "Bronze Sallet";
                    case 0x1BC: return "Iron Sallet";
                    case 0x1BD: return "Mythril Sallet";
                    case 0x1BE: return "Flame Sallet";
                    case 0x1BF: return "Frost Sallet";
                    case 0x1C0: return "Lightning Sallet";
                    case 0x1C1: return "Time Sallet";
                    case 0x1C2: return "Eternal Sallet";
                    case 0x1C3: return "Diamond Sallet";
                    case 0x1C4: return "Bronze Belt";
                    case 0x1C5: return "Iron Belt";
                    case 0x1C6: return "Mythril Belt";
                    case 0x1C7: return "Flame Belt";
                    case 0x1C8: return "Frost Belt";
                    case 0x1C9: return "Lightning Belt";
                    case 0x1CA: return "Pure Belt";
                    case 0x1CB: return "Wind Belt";
                    case 0x1CC: return "Diamond Belt";
                    case 0x1CD: return "Flame Craft";
                    case 0x1CE: return "Frost Craft";
                    case 0x1CF: return "Lightning Craft";
                    case 0x1D0: return "Clockwork";
                    case 0x1D1: return "New Clockwork";
                    case 0x1D2: return "Blue Yarn";
                    case 0x1D3: return "White Yarn";
                    case 0x1D4: return "Gold Craft";
                    case 0x1D5: return "Tome of Wisdom";
                    case 0x1D6: return "Secrets of Wisdom";
                    case 0x1D7: return "Lady's Accessories";
                    case 0x1D8: return "Tome of Speed";
                    case 0x1D9: return "Secrets of Speed";
                    case 0x1DA: return "Book of Brigandology";
                    case 0x1DB: return "Zeal Kit";
                    case 0x1DC: return "Fiend Kit";
                    case 0x1DD: return "Daemon Kit";
                    case 0x1DE: return "Faerie Kit";
                    case 0x1DF: return "Angel Kit";
                    case 0x1E0: return "Ring of Light";
                    case 0x1E1: return "Eyewear Techniques";
                    case 0x1E2: return "Designer Glasses";
                    case 0x1E3: return "Healing Kit";
                    case 0x1E4: return "Fashion Kit";
                    case 0x1E5: return "Goggle Techniques";
                    case 0x1E6: return "Designer Goggles";
                    case 0x1E7: return "Soul of the Lion";
                    case 0x1E8: return "Soul of the Dragon";
                    case 0x1E9: return "Tome of Magic";
                    case 0x1EA: return "Tome of Sorcery";
                    case 0x1EB: return "Forbidden Tome";
                    case 0x1EC: return "Greatest Weapon";
                    case 0x1ED: return "Ring of Invincibility";
                    case 0x1EE: return "design 94 (Unused)";
                    case 0x1EF: return "design 95 (Unused)";
                    case 0x1F0: return "design 96 (Unused)";
                    case 0x1F1: return "design 97 (Unused)";
                    case 0x1F2: return "design 98 (Unused)";
                    case 0x1F3: return "design 99 (Unused)";
                    case 0x1F4: return "design 100 (Unused)";
                    case 0xFFFF: return "null";
                }

                if (itemId >= 0x01F5 && itemId <= 0x7FFF)
                {
                    return "<Invalid> (Lag/Crash)";
                }
                else
                {
                    return "<Invalid>";
                }
            }

            return null;
        }

        /// <summary>
        /// Not used or implemented.
        /// </summary>
        /// <param name="value">Value to be converted.</param>
        /// <param name="targetType">Type to convert to.</param>
        /// <param name="parameter">Optional conversion parameter.</param>
        /// <param name="culture">Globalization info.</param>
        /// <returns>Throws see <see cref="NotImplementedException" />.</returns>
        public Object ConvertBack(Object value, Type targetType, Object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
    //// End class
}
//// End namespace